# UPDATED Render Configuration with SendGrid (US-03)
# Replace your current render.yaml with this file

services:
  - type: web
    name: room-booking-api
    env: python
    region: oregon
    plan: free

    # Build Configuration
    buildCommand: pip install -r requirements.txt

    # Start Command
    startCommand: gunicorn app_enhanced:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info --access-logfile - --error-logfile -

    # Health Check
    healthCheckPath: /

    # Auto-deploy
    autoDeploy: true

    # Environment Variables
    envVars:
      # AWS DynamoDB
      - key: AWS_ACCESS_KEY_ID
        sync: false

      - key: AWS_SECRET_ACCESS_KEY
        sync: false

      - key: AWS_DEFAULT_REGION
        value: us-east-1

      # Flask
      - key: FLASK_ENV
        value: production

      - key: PYTHON_VERSION
        value: 3.11.0

      # US-03: SendGrid Email Configuration
      - key: SENDGRID_API_KEY
        sync: false  # You'll add this manually in Render dashboard

      - key: SENDGRID_FROM_EMAIL
        value: doxdoxdox9@gmail.com # UPDATE THIS with your verified sender email