# CORRECT Render Configuration - Points to app_enhanced.py
# Replace your current render.yaml with this file

services:
  - type: web
    name: room-booking-api
    env: python
    region: oregon
    plan: free

    # Build Configuration
    buildCommand: pip install -r requirements.txt

    # CRITICAL: Point to app_enhanced.py, not app.py!
    startCommand: gunicorn app_enhanced:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info --access-logfile - --error-logfile -

    # Health Check
    healthCheckPath: /

    # Auto-deploy
    autoDeploy: true

    # Environment Variables
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false

      - key: AWS_SECRET_ACCESS_KEY
        sync: false

      - key: AWS_DEFAULT_REGION
        value: us-east-1

      - key: FLASK_ENV
        value: production

      - key: PYTHON_VERSION
        value: 3.11.0